#ifndef ILRD_HRD22_CIRCLE_HPP
#define ILRD_HRD22_CIRCLE_HPP


#include "utils.h"


namespace hrd22
{

class Circle
{
    public:
        explicit Circle(double radius = 0.0); 
        //~Circle() NOEXCEPT; //Dtor autogenerated

    private:
        double m_radius;

        Circle(const Circle& other_); // Copy Ctor do not implement
        Circle& operator=(const Circle& other_); // assignment operator do not implement
};



}
#endif // ILRD_HRD22_CIRCLE_HPP