#ifndef ILRD_HRD22_CIRCLE_HPP
#define ILRD_HRD22_CIRCLE_HPP


#include "utils.h"


namespace hrd22
{

class Rectangle
{
    public:
        explicit Rectangle(double length = 0.0, double width = 0.0); 
        //~Rectangle() NOEXCEPT; //Dtor autogenerated

    private:
        double m_length;
        double m_width;

        Rectangle(const Rectangle& other_); // Copy Ctor do not implement
        Rectangle& operator=(const Rectangle& other_); // assignment operator do not implement
};



}
#endif // ILRD_HRD22_CIRCLE_HPP